language: ruby

rvm:
- 2.3.1

install: gem install jekyll html-proofer
script: bundle install &&  jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: surge
  project: ./_site/
  domain: sebastiankulig.com
  skip_cleanup: true