language: ruby

rvm:
- 2.3.1

install: gem install jekyll
script: bundle install &&  jekyll build -v 3.5.1 # use bundle exec jekyll build if probelm with dependancies and gem versions

deploy:
  provider: surge
  project: _site
  domain: sebastiankulig.com
  skip_cleanup: true