# Site Configuration
source              : source/
destination         : _site/

title               : Sebastian Kulig - Front-end Developer and Web Designer
description         : Responsive and mobile-friendly website design for you and your business. Based in Castlebar, Co. Mayo, Ireland
locale              : en_IE
baseurl             : "" # the subpath of your site, e.g. /blog ++remove++
url                 : "http://www.sebastiankulig.com"

# Site Owner
owner:
  github_username     : sebam2k4
  github_repository   : "sebam2k4/sebastiankulig-Jekyll"
  google_analytics    : UA-80489929-2
  twitter_username    : sebam2k4
  codepen_username    : sebam2k4
  instagram_username  : seb_skdesign
  name                : Sebastian Kulig
  email               : info@sebastiankulig.com
  linkedin_username   :
  flickr_username     :
  facebook_username   :

# Build settings
markdown: kramdown

keep_files:
  - .git

exclude:
  - Gemfile
  - Gemfile.lock
  - readme
  - .sass-cache
  
include:
  - _pages
  - contact.php

 # Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
