source: jekyllSite
destination: ../_site
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sebastian Kulig - Front-end Developer and Web Designer
email: info@sebastiankulig.com
description: Responsive and mobile-friendly website design for you and your business. Based in Castlebar, Co. Mayo, Ireland
baseurl: "" # the subpath of your site, e.g. /blog ++remove++
url: "http://www.sebastiankulig.com" # the base hostname & protocol for your site, e.g. http://example.com ++change to http://www.sebastiankulig.com++
twitter_username: sebam2k4
github_username:  sebam2k4

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed

keep_files:
  - .git

exclude:
  - Gemfile
  - Gemfile.lock
  - readme
  - .sass-cache
  
include:
  - _pages
  - contact.php
  
#plugins
gems:
  - jekyll-sitemap